# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phase < Formula
  desc "Securely manage your secrets and environment variables with Phase."
  homepage "https://github.com/phasehq/cli"
  version "2.3.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phasehq/cli/releases/download/v2.3.1/phase_cli_2.3.1_darwin_amd64"
      sha256 "74007fc26e18782e8e28d2d811053ad9401290dfa0dcdf242dfd25df7825757b"

      define_method(:install) do
        bin.install Dir.glob("phase_cli_*").first => "phase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phasehq/cli/releases/download/v2.3.1/phase_cli_2.3.1_darwin_arm64"
      sha256 "8dd5bd963078587ff9033ac85eb6e86d257438f80f5150de44047700288e4fdb"

      define_method(:install) do
        bin.install Dir.glob("phase_cli_*").first => "phase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phasehq/cli/releases/download/v2.3.1/phase_cli_2.3.1_linux_amd64"
      sha256 "bc20f703fe14a916de60f278e0209215eba91c4f7661869b78a4ab1f25add9c7"
      define_method(:install) do
        bin.install Dir.glob("phase_cli_*").first => "phase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phasehq/cli/releases/download/v2.3.1/phase_cli_2.3.1_linux_arm64"
      sha256 "a8a4e6ed216f32b3a71ebcb255dbef43712675f467f9bdde71a3cd176d7ec881"
      define_method(:install) do
        bin.install Dir.glob("phase_cli_*").first => "phase"
      end
    end
  end

  test do
    system "#{bin}/phase", "--version"
  end
end
