# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phase < Formula
  desc "Securely manage your secrets and environment variables with Phase."
  homepage "https://github.com/phasehq/cli"
  version "2.3.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phasehq/cli/releases/download/v2.3.0/phase_cli_2.3.0_darwin_amd64"
      sha256 "c55091d97ec9cbf43f4471bcf99c63e5c95b290f1618e5b126c25ede6d56902c"

      define_method(:install) do
        bin.install Dir.glob("phase_cli_*").first => "phase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phasehq/cli/releases/download/v2.3.0/phase_cli_2.3.0_darwin_arm64"
      sha256 "934c31465488c1c6d25aff2de6d18b55174d7c5f5b0852a105a04031d7e4b764"

      define_method(:install) do
        bin.install Dir.glob("phase_cli_*").first => "phase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phasehq/cli/releases/download/v2.3.0/phase_cli_2.3.0_linux_amd64"
      sha256 "5ccedc9153563077c75370916c70ca7ad0b6e324b99177a6d5c5e3767f97956f"
      define_method(:install) do
        bin.install Dir.glob("phase_cli_*").first => "phase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phasehq/cli/releases/download/v2.3.0/phase_cli_2.3.0_linux_arm64"
      sha256 "d321bacc405d6c8358b86158e2b5b9a12b096fc4e36793466cd2b1ac9ff4c4e4"
      define_method(:install) do
        bin.install Dir.glob("phase_cli_*").first => "phase"
      end
    end
  end

  test do
    system "#{bin}/phase", "--version"
  end
end
